# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - API/CCW.UserProfile/*
      - API/CCW.Common/*
      - Deployment/Pipelines/azure-api-pipeline-template.yml

pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - template: /Deployment/Pipelines/azure-api-pipeline-template.yml
    parameters:
      azureSubscriptionConnection: 'AZR-GOV-CSSA-SDSD-CCW-D-SP-ADO'
      environment: 'dev'
      backendsvc: 'UserProfile'
      backendsuffix: '001'
      webAppSuffix: '001'
  
  - stage:
    jobs:
      - job:
        steps:
        - task: AzureCLI@2
          displayName: 'Add agent ip address to function network restrictions'
          inputs:
            azureSubscription: 'app-cssa-ccw-ado-prd-001'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              $ErrorActionPreference = "Stop"
                            
              Write-Host "Installing Az.Resources"
              Install-Module Az.Resources -Repository PSGallery -AllowClobber -Force
              
              Write-Host "Installing Az.Accounts"
              Install-Module Az.Accounts -Repository PSGallery -AllowClobber -Force
                            
              Write-Host "Importing Az.Resources"
              Import-Module Az.Resources -Force
              
              Write-Host "Importing Az.Accounts"
              Import-Module Az.Accounts -Force
              
              Write-Host "Changing directory"
              Set-Location $(ScriptFolder)
              Get-ChildItem
              
              Write-Host "Logging into Azure"
              
              $azureAplicationId =$env:servicePrincipalId
              $azureTenantId= $env:tenantId
              $azurePassword = ConvertTo-SecureString $env:servicePrincipalKey -AsPlainText -Force
              
              $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
              Connect-AzAccount -Environment AzureUSGovernment -Credential $psCred -TenantId $azureTenantId  -ServicePrincipal 
              
              Write-Host "Getting local IP Address"
              $ipAddress = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
              
              Import-Module .\Set-AppIPRestriction.psm1
              
              Write-Host "Setting access restriction for local IP Address"
              Set-AppIPRestriction -ResourceGroupName "rg-sdsd-it-ripa-$(env)-001" -FunctionName "sdsd-ripa-$(env)-$(Backendsvc)-fa" -IPAddress $ipAddress -RuleName "AllowAdoDeployment" -RuleAction "Allow" -RulePriority "900"
            
            addSpnToEnvironment: true
            useGlobalConfig: true
            workingDirectory: '$(ScriptFolder)'
  
  - template: /Deployment/Pipelines/azure-api-pipeline-template.yml
    parameters:
      azureSubscriptionConnection: 'app-cssa-ccw-ado-prd-001'
      environment: 'p'
      backendsvc: 'UserProfile'
      backendsuffix: '001'
      webAppSuffix: '1'
