# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    branches:
        include:
            - main
    paths:
        include:
            - API/CCW.UserProfile/*
            - API/CCW.Common/*
            - Deployment/Pipelines/azure-api-pipeline-template.yml

pr: none

pool:
    vmImage: "windows-latest"

stages:
    - template: /Deployment/Pipelines/azure-api-pipeline-template.yml
      parameters:
          azureSubscriptionConnection: "AZR-GOV-CSSA-SDSD-CCW-D-SP-ADO"
          environment: "dev"
          backendsvc: "UserProfile"
          backendsuffix: "001"
          webAppSuffix: "001"

    - template: /Deployment/Pipelines/azure-api-pipeline-template.yml
      parameters:
          azureSubscriptionConnection: "app-cssa-ccw-ado-prd-001"
          environment: "p"
          backendsvc: "UserProfile"
          backendsuffix: "001"
          webAppSuffix: "1"

