# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    branches:
        include:
            - main
    paths:
        include:
            - API/CCW.Document/*
            - API/CCW.Common/*
            - Deployment/Pipelines/azure-api-pipeline-template.yml

pr: none

pool:
    vmImage: "windows-latest"

stages:
    - template: /Deployment/Pipelines/azure-api-pipeline-template.yml
      parameters:
          azureSubscriptionConnection: $(AzureSubscription)
          environment: $(Environment)
          backendsvc: $(BackendSvc)
          backendsuffix: $(BackendSuffix)
          webAppSuffix: $(WebAppSuffix)
