# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'CCW-ADO-SP'
    subscriptionId: 'c74e04b6-0cd7-4778-863e-34654eb49270'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-sdsd-it-ccw-dev-002'
    location: 'USGov Arizona'
    templateLocation: 'Linked artifact'
    csmFile: 'Deployment\IaC\Infrastructure\sandboxTemplate.json'
    csmParametersFile: 'Deployment\IaC\Infrastructure\sandboxTemplate.parameters.json'
    deploymentMode: 'Validation'