trigger:
  branches:
   include:
      - main
  paths:
    include:
      - UI/*
      - Deployment/Pipelines/azure-pipeline-dev.yml


  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Building CCW UI Project"
    
    jobs:
      - job: UI_Build
        displayName: 'Building UI'
        steps:
          - checkout: self
            displayName: "Branch Checkout"
            persistCredentials: true
            fetchDepth: 2

          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: '14.x'

          - script: rm -rf "node_modules"
            displayName: "Purge node modules"
            continueOnError: true
            workingDirectory: UI/

          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: 'ci'
              workingDir: 'UI/'

          - script: npx nx run-many --target=build --base=HEAD~1 --parallel
            displayName: "nx build"
            # condition: eq($(FORCE), 'false')
            continueOnError: true
            workingDirectory: 'UI/'
            
          
          - script: npx nx run-many --target=build --projects=admin,public --prod
            displayName: "nx build force"
            # condition: eq($(FORCE), 'true')
            continueOnError: true
            workingDirectory: 'UI/'

          - bash: |
              if [ -d UI/dist/apps/admin ]; 
              then
                echo "##vso[task.setVariable variable=ADMINEXISTS]true"
                echo "Admin folder exists!"
              else
                echo "Admin folder does not exist"
              fi
            name: check_admin_changes
            displayName: 'Check Admin files'

          - bash: |
              if [ -d UI/dist/apps/public ]; 
              then
                echo "##vso[task.setVariable variable=PUBLICEXISTS]true"
                echo "Public folder exists!"
              else
                echo "Public folder does not exist"
              fi
            name: check_public_changes
            displayName: 'Check Public files'

          - task: CopyFiles@2
            displayName: "Copy Admin Config"
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/UI/apps/admin/config'
              Contents: 'config.json'
              TargetFolder: '$(Build.SourcesDirectory)/UI/dist/apps/admin'

          - task: ArchiveFiles@2
            displayName: "Archive Admin Build files"
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/dist/apps/admin'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-admin.zip'
              replaceExistingArchive: true

          # - task: ArchiveFiles@2
          #   displayName: "Archive Admin Config"
          #   condition: eq(variables['ADMINEXISTS'], 'true')
          #   inputs:
          #     rootFolderOrFile: '$(Build.SourcesDirectory)/UI/apps/admin/config'
          #     includeRootFolder: true
          #     archiveType: 'zip'
          #     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-admin-config.zip'
          #     replaceExistingArchive: true

          - task: CopyFiles@2
            displayName: "Copy Public Config"
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/UI/apps/public/config'
              Contents: 'config.json'
              TargetFolder: '$(Build.SourcesDirectory)/UI/dist/apps/public'

          - task: ArchiveFiles@2
            displayName: "Archive Public Build Files"
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/dist/apps/public'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-public.zip'
              replaceExistingArchive: true

          # - task: ArchiveFiles@2
          #   displayName: "Archive Public Config"
          #   condition: eq(variables['PUBLICEXISTS'], 'true')
          #   inputs:
          #     rootFolderOrFile: '$(Build.SourcesDirectory)/UI/apps/public/config'
          #     includeRootFolder: true
          #     archiveType: 'zip'
          #     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-public-config.zip'
          #     replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: CCW_UI_Dev
    displayName: "CCW-UI-Dev"
    variables:
    - name: environment
      value: DEV
    - group: CCW-UI-$(environment)-PUBLIC


    jobs:
      - job: Deploy_Dev
        displayName: 'Deploy Dev'
        steps:

          - task: DownloadBuildArtifacts@0
            displayName: 'Download Artifacts'
            inputs:
              buildtype: 'current'
              downloadtype: 'single'
              artifactName: 'drop'
              downloadPath: $(Build.ArtifactStagingDirectory)
     
        # - task: DownloadPipelineArtifact@2
        #   inputs:
        #     buildType: 'current'
        #     artifactName: 'drop'
        #     targetPath: '$(Pipeline.Workspace)'

        # - task: DownloadBuildArtifacts@1
        #   inputs:
        #     buildType: 'current'
        #     downloadType: 'single'
        #     downloadPath: '$(System.ArtifactsDirectory)'
          
          - script: ls -la $(Agent.BuildDirectory)/

          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              destinationFolder: '$(System.DefaultWorkingDirectory)/UI/drop'
              cleanDestinationFolder: false
              overwriteExistingFiles: true

          - bash: |
              if [ -d UI/drop/apps/admin ]; 
              then
                echo "##vso[task.setVariable variable=ADMINEXISTS]true"
                echo "Admin folder exists!"
              else
                echo "Admin folder does not exist"
              fi
            name: check_admin_changes
            displayName: 'Check Admin files'

          - bash: |
              if [ -d UI/drop/apps/public ]; 
              then
                echo "##vso[task.setVariable variable=PUBLICEXISTS]true"
                echo "Public folder exists!"
              else
                echo "Public folder does not exist"
              fi
            name: check_public_changes
            displayName: 'Check Public files'

          - task: replacetokens@5
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              targetFiles: '**/admin/config.json'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true

          - task: replacetokens@5
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              targetFiles: '**/public/config.json'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true

          - task: AzureCLI@2
            displayName: 'Azure CLI Upload'
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              azureSubscription: 'CCW-ADO-SP'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: 'az storage blob upload-batch -d ''$web'' --account-name ''sasdsditccwdev002''  -s ''./apps/admin'' --overwrite ''true'''
              workingDirectory: '$(System.DefaultWorkingDirectory)/UI/drop'

          - task: AzureCLI@2
            displayName: 'Azure CLI Upload'
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              azureSubscription: 'CCW-ADO-SP'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: 'az storage blob upload-batch -d ''$web'' --account-name ''sasdsditccwdev003''  -s ''./apps/public'' --overwrite ''true'''
              workingDirectory: '$(System.DefaultWorkingDirectory)/UI/drop'

              #''sdsdccwdev''$(Website-storage-Acc)''sa''
#############################################################################################
#Purge CDN
# - task: AzureCLI@2
#   displayName: 'Azure CLI Purge CDN'
#   inputs:
#     azureSubscription: 'sdsd-dev'
#     scriptType: bash
#     scriptLocation: inlineScript
#     inlineScript: 'az cdn endpoint purge -g rg-cssa-it-ops-shd -n ripa-dev-sdsd-cdn-ep --profile-name cssa-global-cdn --content-paths "/*" --debug --verbose'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/RIPA-UI/drop'
#############################################################################################