trigger: none

pr: none

pool:
  vmImage: windows-latest

variables:
- template: variables/marketplace-install-vars.yml
- name: mpPath
  value: 'Deployment\IaC\Infrastructure\Marketplace'

stages:
  - stage: MP_Publish_Package
    displayName: 'MP Publish Package'

    jobs:
      - job: MP_Publish_Package
        displayName: 'MP Publish Package'

        steps:
        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - UI'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'CCW-UI'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-UI'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - Admin API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-Admin'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-Admin'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - App API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-Application'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-Application'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - Doc API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-Document'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-Document'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - Payment API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-Payment'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-Payment'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - Sched API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-Schedule'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-Schedule'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts - User API'
          inputs:
            buildType: 'specific'
            project: 'CSSA-CCW'
            pipeline: 'API-UserProfile'
            buildVersionToDownload: 'latest'
            branchName: 'main'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)/_CCW-UserProfile'

        - task: AzureKeyVault@2
          displayName: 'Azure Key Vault: $(CSSA_CERT_KEY_VAULT_NAME)'
          inputs:
            azureSubscription: '$(CSSA_SHD_SUBSCRIPTION_ID)'
            KeyVaultName: '$(CSSA_CERT_KEY_VAULT_NAME)'

        - template: templates/logging_tasks.yml

        - template: templates/logging_tasks.yml
          parameters:
            workingDirectory: '$(System.ArtifactsDirectory)'
