trigger:
  branches:
   include:
      - main
  paths:
    include:
      - UI/*
      - Deployment/Pipelines/azure-pipeline-dev.yml

stages:
  - stage: CCW_UI_Dev
    displayName: "CCW-UI-Dev"
    
    jobs:
      - job: Deploy_Dev
        displayName: 'Deploy Dev'
        steps:

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts'
          inputs:
            downloadPath: $(Build.ArtifactStagingDirectory)

        - task: ExtractFiles@1
          displayName: 'Extract files'
          inputs:
            destinationFolder: '$(System.DefaultWorkingDirectory)/UI/drop'
            cleanDestinationFolder: false
            overwriteExistingFiles: true

        - task: AzureCLI@2
          displayName: 'Azure CLI Upload'
          inputs:
            azureSubscription: 'CCW-ADO-SP'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: 'az storage blob upload-batch -d ''$web'' --account-name ''sdsdccwdev''$(Website-storage-Acc)''sa''  -s ''./dist'' --overwrite ''true'''
            workingDirectory: '$(System.DefaultWorkingDirectory)/UI/drop'
#############################################################################################
#Purge CDN
# - task: AzureCLI@2
#   displayName: 'Azure CLI Purge CDN'
#   inputs:
#     azureSubscription: 'sdsd-dev'
#     scriptType: bash
#     scriptLocation: inlineScript
#     inlineScript: 'az cdn endpoint purge -g rg-cssa-it-ops-shd -n ripa-dev-sdsd-cdn-ep --profile-name cssa-global-cdn --content-paths "/*" --debug --verbose'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/RIPA-UI/drop'
#############################################################################################