# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
   include:
      - main
  paths:
    include:
      - UI/*
      - Deployment/Pipelines/azure-pipeline-ui.yml

parameters:
  - name: shouldBuildAll
    type: boolean
    default: false

variables:
  DATE_COUNTER: $[counter(format('UI{0:yyyy}{0:MM}{0:dd}', pipeline.startTime), 1)]

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Building CCW UI Project"
    
    jobs:
      - job: UI_Build
        displayName: 'Building UI'
        steps:
          - checkout: self
            displayName: "Branch Checkout"
            persistCredentials: true
            fetchDepth: 2

          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: '14.x'

          - script: rm -rf "node_modules"
            displayName: "Purge node modules"
            continueOnError: true
            workingDirectory: UI/

          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: 'ci'
              workingDir: 'UI/'

          - script: npx nx affected --target=build --base=HEAD~1 --parallel
            displayName: "nx build affected"
            condition: ${{ eq(parameters.shouldBuildAll, false) }}
            workingDirectory: 'UI/'

          - script: npx nx run-many --target=build --projects=admin,public --prod --parallel
            displayName: "nx build all"
            condition: ${{ parameters.shouldBuildAll }}
            workingDirectory: 'UI/'

          - bash: |
              if [ -d UI/dist/apps/admin ]; 
              then
                echo "##vso[task.setVariable variable=ADMINEXISTS]true"
                echo "Admin folder exists!"
              else
                echo "Admin folder does not exist"
              fi
            name: check_admin_changes
            displayName: 'Check Admin files'

          - bash: |
              if [ -d UI/dist/apps/public ]; 
              then
                echo "##vso[task.setVariable variable=PUBLICEXISTS]true"
                echo "Public folder exists!"
              else
                echo "Public folder does not exist"
              fi
            name: check_public_changes
            displayName: 'Check Public files'

          - task: CopyFiles@2
            displayName: "Copy Admin Config"
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/UI/apps/admin'
              Contents: '*.config.json'
              TargetFolder: '$(Build.SourcesDirectory)/UI/dist/apps/admin'

          - task: ArchiveFiles@2
            displayName: "Archive Admin Build files"
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/dist/apps/admin'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/admin.zip'
              replaceExistingArchive: true

          - task: ArchiveFiles@2
            displayName: "Archive Admin Config"
            condition: eq(variables['ADMINEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/apps/admin/config'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/admin-config.zip'
              replaceExistingArchive: true

          - task: CopyFiles@2
            displayName: "Copy Public Config"
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/UI/apps/public'
              Contents: '*.config.json'
              TargetFolder: '$(Build.SourcesDirectory)/UI/dist/apps/public'

          - task: ArchiveFiles@2
            displayName: "Archive Public Build Files"
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/dist/apps/public'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/public.zip'
              replaceExistingArchive: true

          - task: ArchiveFiles@2
            displayName: "Archive Public Config"
            condition: eq(variables['PUBLICEXISTS'], 'true')
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/UI/apps/public/config'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/public-config.zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: "Deploy"
    dependsOn: Build
    
    jobs:
      - job: Deploy_Public_UI
        displayName: 'Deploy Public UI'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download artifact
            inputs:
              path: '$(Agent.BuildDirectory)'

          - powershell: |
              $fileExists = Test-Path -Path "$(Agent.BuildDirectory)/drop/public.zip"
              Write-Output "##vso[task.setvariable variable=PUBLICZIPEXISTS]$fileExists"
              Write-Host "PUBLICZIPEXISTS" $fileExists"
            displayName: 'Check Public files'

          # - task: ExtractFiles@1
          #   inputs:
          #     archiveFilePatterns: '$(Agent.BuildDirectory)/drop/admin.zip'
          #     destinationFolder: '$(System.ArtifactsDirectory)/admin'
          #     cleanDestinationFolder: true
          #     overwriteExistingFiles: true

          # - task: ExtractFiles@1
          #   inputs:
          #     archiveFilePatterns: '$(Agent.BuildDirectory)/drop/admin-config.zip'
          #     destinationFolder: '$(System.ArtifactsDirectory)/admin-config'
          #     cleanDestinationFolder: true
          #     overwriteExistingFiles: true

          - task: ExtractFiles@1
            displayName: "Extract Public UI"
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')
            inputs:
              archiveFilePatterns: '$(Agent.BuildDirectory)/drop/public.zip'
              destinationFolder: '$(System.ArtifactsDirectory)/public'
              cleanDestinationFolder: true
              overwriteExistingFiles: true

          - task: ExtractFiles@1
            displayName: "Extract Public config"
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')
            inputs:
              archiveFilePatterns: '$(Agent.BuildDirectory)/drop/public-config.zip'
              destinationFolder: '$(System.ArtifactsDirectory)/public-config'
              cleanDestinationFolder: true
              overwriteExistingFiles: true

          - script: ls -la $(System.ArtifactsDirectory)
          # - script: ls -la $(System.ArtifactsDirectory)/admin-config
          - script: ls -la $(System.ArtifactsDirectory)/public
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')
          - script: ls -la $(System.ArtifactsDirectory)/public-config
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')
          # - script: cat $(System.ArtifactsDirectory)/admin-config/config.json
          - script: cat $(System.ArtifactsDirectory)/public-config/config.json
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')

          - powershell: |
              Set-Location $(System.ArtifactsDirectory)
              
              Get-ChildItem
              
              $environmentName = switch ($env:env)
              {
                  "dev" { "dev" }
                  "uat" { "qa" }
                  "prd" { "prod" }
              }
              
              Write-Host "Copying for $($environmentName)"
              
              $configContent = Get-Content -Path "$(System.ArtifactsDirectory)/public-config/config.json"
              
              Set-Content -Path "$(System.ArtifactsDirectory)/public/config.json" -Value $configContent 
              
              Get-ChildItem -Path $(System.ArtifactsDirectory)/public
              
              Get-Content -Path "$(System.ArtifactsDirectory)/public/config.json"
            displayName: 'PowerShell Script'
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')

          - task: AzureCLI@2
            displayName: 'Publish Website'
            condition: eq(variables['PUBLICZIPEXISTS'], 'True')
            inputs:
              azureSubscription: 'CCW-ADO-SP'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: 'az storage blob upload-batch -d ''$web'' --account-name sasdsditccwdevpui001  -s ''./public'' --overwrite ''true'''
              workingDirectory: '$(System.ArtifactsDirectory)'
